name: s3-db-bump

on:
  push:
    tags:
      - "v*"

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
      
      